ARG DIR_ROOT=/app
FROM node:18
ARG DIR_ROOT

WORKDIR ${DIR_ROOT}

COPY packages/moviemasher.js/package.json ${DIR_ROOT}/node_modules/@moviemasher/moviemasher.js/package.json
COPY packages/client-core/package.json ${DIR_ROOT}/node_modules/@moviemasher/client-core/package.json
COPY packages/client-react/package.json ${DIR_ROOT}/node_modules/@moviemasher/client-react/package.json
COPY packages/protocol-supabase/package.json ${DIR_ROOT}/node_modules/@moviemasher/protocol-supabase/package.json
COPY packages/theme-default/package.json ${DIR_ROOT}/node_modules/@moviemasher/theme-default/package.json

COPY workspaces/example-supabase/package.json ${DIR_ROOT}/package.json

RUN npm install 

LABEL org.opencontainers.image.authors="support@moviemasher.com"

ENTRYPOINT ["npm", "run"]
CMD ["build"]
