// this file is automatically generated from template at
// workspaces/translate/src/rollup.config.mjs

import { rollupConfigurations} from "../../../../dev/utils/rollupConfigurations.mjs"

const framework = 'framework'
const libName = `client-${framework}`
const name = `MovieMasherClient`
const extension = 'js'
const configurations = rollupConfigurations({ name, libName, extension })
export default configurations
