version: "3"
networks:
  default:
    name: moviemasher-example-react
services:
  moviemasher-example-react:
    image: httpd:2.4
    container_name: moviemasher-example-react-8578
    ports:
      - 8578:80
    volumes:
      - ../src/index.html:/usr/local/apache2/htdocs/index.html
      - ../../../../dev/img/favicon.ico:/usr/local/apache2/htdocs/favicon.ico
      - ../../../packages/moviemasher.js/umd/moviemasher.js:/usr/local/apache2/htdocs/moviemasher.js
      - ../../../packages/theme-default/umd/theme-default.js:/usr/local/apache2/htdocs/theme-default.js
      - ../../../packages/theme-default/moviemasher.css:/usr/local/apache2/htdocs/moviemasher.css
      - ../../../packages/client-react/umd/client-react.js:/usr/local/apache2/htdocs/client-react.js
      - ../../../packages/client-react/umd/client-react.min.js:/usr/local/apache2/htdocs/client-react.min.js
      - ../../../node_modules/react/umd/react.development.js:/usr/local/apache2/htdocs/react.development.js
      - ../../../node_modules/react-dom/umd/react-dom.development.js:/usr/local/apache2/htdocs/react-dom.development.js
      