ARG DIR_ROOT=/app
FROM node:18
ARG DIR_ROOT

WORKDIR ${DIR_ROOT}

# COPY package.json ${DIR_ROOT}/package.json
COPY packages ${DIR_ROOT}/packages
COPY workspaces ${DIR_ROOT}/workspaces
COPY examples ${DIR_ROOT}/examples
COPY images ${DIR_ROOT}/images

COPY dev/utils ${DIR_ROOT}/dev/utils
RUN node dev/build/cli.mjs --output=${DIR_ROOT}/package.json
RUN npm install 
# RUN npm install -g npm

LABEL org.opencontainers.image.authors="support@moviemasher.com"

ENTRYPOINT ["npm", "run"]
CMD ["all"]
