version: "3"
networks:
  default:
    name: tester
services:
  tester:
    build:
      dockerfile: dev/test/Dockerfile.cnf
      context: ../../
    image: moviemasher/moviemasher.tester:5.1.0
    container_name: moviemasher-tester
    entrypoint: npm run jest -w tester
    command: test.e2e.ts
    volumes:
      - ../../dev/:/home/node/app/dev/
      - ../../packages/:/home/node/app/packages/
      - ../../temporary/test:/home/node/app/temporary/test
      - ../../workspaces/example-express-react/:/home/node/app/workspaces/example-express-react/
      - ../tester/:/home/node/app/workspaces/tester/
      - ./jest-puppeteer.config.js:/home/node/app/jest-puppeteer.config.js
      - ./jest.config.js:/home/node/app/jest.config.js
      - ../../packages/moviemasher.js/src/:/home/node/app/packages/moviemasher.js/src/


  tester-old:
    build:
      dockerfile: dev/test/Dockerfile.cnf
      context: ../../
    image: moviemasher/moviemasher.tester:5.1.0
    container_name: moviemasher-tester
    command: test.e2e.ts
    volumes:
      - ../../packages/server-express:/home/node/app/packages/server-express
      - ../../temporary/test-empty-1/:/home/node/app/packages/moviemasher.js/dist/

