import type { BooleanDataType, DataType, NumberDataType, StringDataType } from './DataType.js'

export const BOOLEAN: BooleanDataType = 'boolean'
export const NUMBER: NumberDataType = 'number'
export const STRING: StringDataType = 'string'
export const CONTAINER_ID: DataType = 'containerid'
export const CONTENT_ID: DataType = 'contentid'
export const FRAME = 'frame'
export const PERCENT: DataType = 'percent'
export const RGB: DataType = 'rgb'
