version: "3"
name: moviemasher-example-static
services:
  service:
    image: httpd:2.4
    container_name: moviemasher-example-static-8574
    ports:
      - 8574:80
    volumes:
      - ../../../dev/img/favicon.ico:/usr/local/apache2/htdocs/favicon.ico
      - ../../../packages/@moviemasher/shared-lib/dist/:/usr/local/apache2/htdocs/@moviemasher/shared-lib/dist
      - ../../../packages/@moviemasher/client-lib/dist/:/usr/local/apache2/htdocs/@moviemasher/client-lib/dist
      - ../../../packages/@moviemasher/client-lib/json/:/usr/local/apache2/htdocs/json
      - ../../../examples/static/index.html:/usr/local/apache2/htdocs/index.html
      - ../../../node_modules/@lit:/usr/local/apache2/htdocs/@lit/
      - ../../../node_modules/@lit-labs:/usr/local/apache2/htdocs/@lit-labs/
      - ../../../node_modules/lit:/usr/local/apache2/htdocs/lit/
      - ../../../node_modules/lit-html:/usr/local/apache2/htdocs/lit-html/
      - ../../../node_modules/lit-element:/usr/local/apache2/htdocs/lit-element/
      
