version: "3"
name: moviemasher-node-ffmpeg
services:
 service:
    env_file:
      - ../../../../../dev/local.env
    build: 
      context: ../../../../../
      dockerfile: images/node-ffmpeg/dev/Dockerfile.cnf
    image: moviemasher/node-ffmpeg:${MOVIEMASHER_VERSION}
    command: node --loader tsx --test packages/core/server/dev/test/
    volumes:
      - ../../../../../dev/:${MOVIEMASHER_DIR_ROOT}/dev/
      - ../../../../../images/:${MOVIEMASHER_DIR_ROOT}/images/
      - ../../../../../packages/core/lib/:${MOVIEMASHER_DIR_ROOT}/packages/core/lib/
      - ../../../../../packages/core/server/:${MOVIEMASHER_DIR_ROOT}/packages/core/server/
      - ../../../../../package.json:${MOVIEMASHER_DIR_ROOT}/package.json
      - ../../../../../temporary:${MOVIEMASHER_DIR_ROOT}/temporary
