FROM moviemasher/moviemasher.js:5.0.7
LABEL org.opencontainers.image.authors="support@moviemasher.com"

COPY dev/image/sh/test-build.sh /home/node/app/dev/image/sh/test-build.sh
RUN sh /home/node/app/dev/image/sh/test-build.sh

COPY dev/test/package.json /home/node/app/workspaces/test/package.json
COPY dev/tester/package.json /home/node/app/workspaces/tester/package.json
RUN npm install
RUN rm -R /home/node/app/workspaces/test
RUN rm -R /home/node/app/workspaces/tester

ENTRYPOINT ["npm", "run", "test"]
CMD [""]
