version: "3"
name: moviemasher-example-react
services:
  service:
    image: httpd:2.4
    container_name: moviemasher-example-react-8578
    ports:
      - 8578:80
    volumes:
      - ../../../../dev/img/favicon.ico:/usr/local/apache2/htdocs/favicon.ico
      - ../../../../packages/core/lib/umd/moviemasher.js:/usr/local/apache2/htdocs/moviemasher.js
      - ../../../../packages/core/client/umd/client-core.js:/usr/local/apache2/htdocs/client-core.js

      - ../../../../packages/client/react/umd/client-react.js:/usr/local/apache2/htdocs/client-react.js
      - ../../../../packages/example/react/src/index.html:/usr/local/apache2/htdocs/index.html
