version: "3"
name: moviemasher-tester
services:
  service:
    env_file:
      - ../../../dev/local.env
      - ./test.env
    build: 
      context: ../../../
      dockerfile: images/tester/dev/Dockerfile.cnf
    image: moviemasher/tester:${MOVIEMASHER_VERSION}
    container_name: moviemasher-tester:${MOVIEMASHER_VERSION}
    volumes:
      - ../../../dev:/${MOVIEMASHER_DIR_ROOT}/dev
      - ../../../images/tester:/${MOVIEMASHER_DIR_ROOT}/images/tester
      - ../../../temporary/tester/cache:${MOVIEMASHER_DIR_ROOT}/temporary/cache
      - ../../../temporary/tester/render:${MOVIEMASHER_DIR_ROOT}/temporary/render

      # use latest packages from host computer instead of image
      # - ../private/server.mjs:${MOVIEMASHER_DIR_ROOT}/packages/example/standalone/private/server.mjs
      - ../../../packages/core/lib:${MOVIEMASHER_DIR_ROOT}/packages/core/lib
      - ../../../packages/core/server:${MOVIEMASHER_DIR_ROOT}/packages/core/server
      - ../../../packages/core/client:${MOVIEMASHER_DIR_ROOT}/packages/core/client
      - ../../../packages/server/express:${MOVIEMASHER_DIR_ROOT}/packages/server/express
   
      # use latest client and theme UMD modules from host computer instead of image
      # - ../public/client.js:${MOVIEMASHER_DIR_ROOT}/packages/example/standalone/public/client.js
      # - ../../../packages/core/lib/umd/moviemasher.js:${MOVIEMASHER_DIR_ROOT}/packages/example/standalone/public/moviemasher.js
      # - ../../../packages/client/react/umd/client-react.js:${MOVIEMASHER_DIR_ROOT}/packages/example/standalone/public/client-react.js
      # - ../../../packages/core/client/umd/client-core.js:${MOVIEMASHER_DIR_ROOT}/packages/example/standalone/public/client-core.js

      # - ../../../temporary/standalone:${MOVIEMASHER_DIR_ROOT}/temporary/standalone
    entrypoint: node --experimental-global-customevent --experimental-json-modules --test 
    command: packages
