ARG DIR_ROOT=/app
FROM moviemasher/node-ffmpeg:5.1.2
ARG DIR_ROOT

COPY packages ${DIR_ROOT}/packages
COPY images/tester ${DIR_ROOT}/images/tester

RUN npm install 

LABEL org.opencontainers.image.authors="support@moviemasher.com"

ENTRYPOINT ["node", "--experimental-global-customevent --experimental-json-modules --test"]
CMD ["packages"]
