version: "3"
networks:
  default:
    name: moviemasher-example-express
services:
  moviemasher-example-express:
    build:
      dockerfile: ../../../dev/image/Dockerfile.cnf
      context: ../../../
    image: moviemasher/moviemasher.js:5.1.1
    container_name: moviemasher-example-express-8572
    ports:
      - "8572:8572"
    volumes:
      - ../src/index.html:/home/node/app/workspaces/example-express/host/public/index.html
      - ../../../packages/server-express/cjs:/home/node/app/packages/server-express/cjs
      - ../../../packages/moviemasher.js/esm:/home/node/app/packages/moviemasher.js/esm
      - ../../../packages/moviemasher.js/umd:/home/node/app/packages/moviemasher.js/umd
      - ../../../packages/server-express/package.json:/home/node/app/packages/server-express/package.json
      - ../../../packages/moviemasher.js/package.json:/home/node/app/packages/moviemasher.js/package.json
      - ../../../temporary/example-express/media:/home/node/app/workspaces/example-express/host/public/media
      - ../../../workspaces/example-express/host/server.js:/home/node/app/workspaces/example-express/host/server.js
    command: start workspaces/example-express/host/server.js