ARG DIR_ROOT=/app

FROM node:18 as base
ARG DIR_ROOT
WORKDIR ${DIR_ROOT}

COPY package.json ${DIR_ROOT}/package.json

RUN npm install 

FROM base as stage
ARG DIR_ROOT
COPY images/build-packages/package.json ${DIR_ROOT}/images/build-packages/package.json

COPY examples/express/package.json ${DIR_ROOT}/examples/express//package.json
COPY images/build-docs/package.json ${DIR_ROOT}/images/build-docs//package.json
COPY packages/runtime/server/package.json ${DIR_ROOT}/packages/runtime/server/package.json
COPY packages/runtime/client/package.json ${DIR_ROOT}/packages/runtime/client/package.json
COPY packages/runtime/shared/package.json ${DIR_ROOT}/packages/runtime/shared/package.json
COPY packages/lib/shared/package.json ${DIR_ROOT}/packages/lib/shared/package.json
COPY packages/lib/client/package.json ${DIR_ROOT}/packages/lib/client/package.json
COPY packages/lib/server/package.json ${DIR_ROOT}/packages/lib/server/package.json

RUN npm install 

FROM base
ARG DIR_ROOT

COPY --from=stage ${DIR_ROOT}/node_modules ${DIR_ROOT}/node_modules

ENTRYPOINT ["npm", "run", "--workspace=@moviemasher/build-packages"]
CMD ["build"]
LABEL org.opencontainers.image.authors="support@moviemasher.com"