ARG DIR_ROOT=/app

FROM node:18 as base
ARG DIR_ROOT
WORKDIR ${DIR_ROOT}

COPY package.json ${DIR_ROOT}/package.json

RUN npm install 

FROM base as stage
ARG DIR_ROOT
COPY images/build-packages/package.json ${DIR_ROOT}/images/build-packages/package.json

COPY images/build-docs/package.json ${DIR_ROOT}/images/build-docs//package.json
COPY packages/@moviemasher/client-lib/package.json ${DIR_ROOT}/packages/@moviemasher/client-lib/package.json
COPY packages/@moviemasher/client-react/package.json ${DIR_ROOT}/packages/@moviemasher/client-react/package.json
COPY packages/@moviemasher/server-express/package.json ${DIR_ROOT}/packages/@moviemasher/server-express//package.json
COPY packages/@moviemasher/server-lib/package.json ${DIR_ROOT}/packages/@moviemasher/server-lib/package.json
COPY packages/@moviemasher/shared-lib/package.json ${DIR_ROOT}/packages/@moviemasher/shared-lib/package.json

RUN npm install 

FROM base
ARG DIR_ROOT

COPY --from=stage ${DIR_ROOT}/node_modules ${DIR_ROOT}/node_modules

ENTRYPOINT ["npm", "run", "--workspace=@moviemasher/build-packages"]
CMD ["build"]
LABEL org.opencontainers.image.authors="support@moviemasher.com"