export const BasenameCache = 'cached'
export const BasenameRendering = 'rendering'
export const BasenameDefinition = 'definition'
export const ExtensionLoadedInfo = 'info.txt'
export const ExtensionCommands = 'commands.txt'
