version: "3"
name: moviemasher-server-express
services:
  service:
    env_file:
      - ../../../../dev/local.env
    build: 
      platform: 
        - linux/amd64
        - linux/arm64
      context: ../../../../
      dockerfile: packages/@moviemasher/server-express/dev/Dockerfile.cnf
    image: moviemasher/server-express:${MOVIEMASHER_VERSION}
    container_name: moviemasher-server-express-${MOVIEMASHER_EXAMPLE_PORT}
    # entrypoint: node_modules/pm2/bin/pm2-docker
    entrypoint: node
    command: packages/@moviemasher/server-express/dist/server.js
    environment:
      MOVIEMASHER_EXAMPLE_PORT: ${MOVIEMASHER_EXAMPLE_PORT}
      MOVIEMASHER_EXAMPLE_ROOT: ${MOVIEMASHER_EXAMPLE_ROOT}
      MOVIEMASHER_SHARED_ASSETS: ${MOVIEMASHER_DIR_ROOT}/packages/@moviemasher/client-lib/dist/json/asset-objects.json
      MOVIEMASHER_DEBUG: 1
    ports:
      - ${MOVIEMASHER_EXAMPLE_PORT}:${MOVIEMASHER_EXAMPLE_PORT}
    volumes:
      - ../../../../docs:${MOVIEMASHER_DIR_ROOT}/docs
      - ../../../../packages:${MOVIEMASHER_DIR_ROOT}/packages
      - ../../../../temporary:${MOVIEMASHER_DIR_ROOT}/temporary
