ARG DIR_ROOT=/app

FROM node:18 as base
ARG DIR_ROOT
WORKDIR ${DIR_ROOT}
COPY package.json ${DIR_ROOT}/package.json
RUN npm install 

FROM base as stage
ARG DIR_ROOT
COPY images/test-client/package.json ${DIR_ROOT}/images/test-client/package.json

COPY packages/client/component/package.json ${DIR_ROOT}/packages/client/component/package.json
COPY packages/core/lib/package.json ${DIR_ROOT}/packages/core/lib/package.json
COPY packages/core/client/package.json ${DIR_ROOT}/packages/core/client/package.json
COPY packages/core/server/package.json ${DIR_ROOT}/packages/core/server/package.json
COPY packages/runtime/shared/package.json ${DIR_ROOT}/packages/runtime/shared/package.json
COPY packages/runtime/client/package.json ${DIR_ROOT}/packages/runtime/client/package.json

RUN npm install 


FROM base 
ARG DIR_ROOT

COPY --from=stage ${DIR_ROOT}/node_modules ${DIR_ROOT}/node_modules

RUN npx playwright install --with-deps


ENTRYPOINT ["npm", "run", "--workspace=@moviemasher/test-client"]
CMD ["test"]

LABEL org.opencontainers.image.authors="support@moviemasher.com"