version: "3"
name: moviemasher-test-client
services:
  service:
    build:
      dockerfile: images/test-client/dev/Dockerfile.cnf
      context: ../../../
    image: moviemasher/test-client:${MOVIEMASHER_VERSION}
    # environment:
    #   - CHROME_PATH=/usr/bin/chromium-browser
    # working_dir: /app
    # entrypoint: npm init @open-wc -- '--destinationPath=/app --type=scaffold --scaffoldType=wc --features=testing --typescript=true --tagName=@moviemasher/mono-repo --writeToDisk=true --installDependencies=true'
    # entrypoint: 'cat ./package.json'
    container_name: moviemasher-test-client
    env_file:
      - ../../../dev/local.env
    volumes:
      - ../../../package.json:${MOVIEMASHER_DIR_ROOT}/package.json
      - ../../../images/test-client:${MOVIEMASHER_DIR_ROOT}/images/test-client
      - ../../../dev/:${MOVIEMASHER_DIR_ROOT}/dev/
      - ../../../packages/runtime/shared:${MOVIEMASHER_DIR_ROOT}/packages/runtime/shared
      - ../../../packages/runtime/client:${MOVIEMASHER_DIR_ROOT}/packages/runtime/client
      - ../../../packages/lib/shared:${MOVIEMASHER_DIR_ROOT}/packages/lib/shared
      - ../../../packages/lib/client:${MOVIEMASHER_DIR_ROOT}/packages/lib/client
      