version: "3"
name: moviemasher-builder
services:
  service:
    build:
      dockerfile: images/builder/dev/Dockerfile.cnf
      context: ../../../
    image: moviemasher/builder:${MOVIEMASHER_VERSION}
    container_name: moviemasher-builder
    env_file:
      - ../../../dev/local.env
    volumes:
      - ../../../dev/:${MOVIEMASHER_DIR_ROOT}/dev/
      - ../../../images/:${MOVIEMASHER_DIR_ROOT}/images/
      - ../../../packages/:${MOVIEMASHER_DIR_ROOT}/packages/
      - ../../../workspaces/:${MOVIEMASHER_DIR_ROOT}/workspaces/

      - ../../../images/builder/package.json:${MOVIEMASHER_DIR_ROOT}/package.json

      - ../../../workspaces/documentation/dev/tsconfig.json:${MOVIEMASHER_DIR_ROOT}/tsconfig.json
      - ../../../workspaces/documentation/dev/typedoc.js:${MOVIEMASHER_DIR_ROOT}/typedoc.js
      - ../../../docs/:${MOVIEMASHER_DIR_ROOT}/docs/
      - ../../../README.md:${MOVIEMASHER_DIR_ROOT}/README.md