version: "3"
services:
  moviemasher:
    build:
      dockerfile: ./dev/image/Dockerfile.cnf
      context: ../../
    image: moviemasher/moviemasher.js:5.0.7
    container_name: moviemasher
    ports:
      - "8570:8570"
      - "8571:8571"
    volumes:
      - ./server-config.json:/home/node/app/workspaces/example-express-react/dist/server-config.json
      - ../../temporary/media:/home/node/app/workspaces/example-express-react/dist/public/media/username
      - ../../temporary/data:/home/node/app/workspaces/example-express-react/dist/data
