FROM amazonlinux:2.0.20220316.0
LABEL org.opencontainers.image.authors="support@moviemasher.com"

WORKDIR /home/node/app

# COPY dev/ /home/node/app/dev/
# COPY packages/ /home/node/app/packages/
# COPY workspaces/ /home/node/app/workspaces/
# COPY package.json /home/node/app/package.json
# COPY package-lock.json /home/node/app/package-lock.json
# RUN sh /home/node/app/dev/image/build-clean.sh

COPY dev/image/sh/options.sh /home/node/app/dev/image/sh/options.sh
COPY dev/image/sh/tools-build.sh /home/node/app/dev/image/sh/tools-build.sh
RUN sh /home/node/app/dev/image/sh/tools-build.sh

COPY dev/image/sh/avlibs-build.sh /home/node/app/dev/image/sh/avlibs-build.sh
RUN sh /home/node/app/dev/image/sh/avlibs-build.sh

COPY dev/image/sh/ffmpeg-build.sh /home/node/app/dev/image/sh/ffmpeg-build.sh
RUN sh /home/node/app/dev/image/sh/ffmpeg-build.sh

# COPY dev/image/sh/node-build.sh /home/node/app/dev/image/sh/node-build.sh
# RUN sh /home/node/app/dev/image/sh/node-build.sh

# COPY dev/image/sh/python3-build.sh /home/node/app/dev/image/sh/python3-build.sh
# RUN sh /home/node/app/dev/image/sh/python3-build.sh

# COPY package.json /home/node/app/package.json
# COPY package-lock.json /home/node/app/package-lock.json
# COPY packages/client-react/package.json /home/node/app/packages/client-react/package.json
# COPY packages/moviemasher.js/package.json /home/node/app/packages/moviemasher.js/package.json
# COPY packages/server-express/package.json /home/node/app/packages/server-express/package.json
# RUN npm install

# COPY dev/image/sh/python3-clean.sh /home/node/app/dev/image/sh/python3-clean.sh
# RUN sh /home/node/app/dev/image/sh/python3-clean.sh

# COPY dev/image/sh/ffmpeg-clean.sh /home/node/app/dev/image/sh/ffmpeg-clean.sh
# RUN sh /home/node/app/dev/image/sh/ffmpeg-clean.sh

# COPY dev/image/sh/avlibs-clean.sh /home/node/app/dev/image/sh/avlibs-clean.sh
# RUN sh /home/node/app/dev/image/sh/avlibs-clean.sh

# COPY dev/image/sh/tools-clean.sh /home/node/app/dev/image/sh/tools-clean.sh
# RUN sh /home/node/app/dev/image/sh/tools-clean.sh

# COPY dev/ /home/node/app/dev/
# COPY packages/ /home/node/app/packages/
# COPY workspaces/ /home/node/app/workspaces/
# RUN npm run build

COPY docs/ /home/node/app/docs/

ENTRYPOINT ["node_modules/pm2/bin/pm2-docker"]
CMD ["start", "workspaces/example-express-react/dist/server.js"]
