version: "3"
services:
  moviemasher:
    build:
      dockerfile: ./dev/image/Dockerfile.cnf
      context: ../../
    image: moviemasher/moviemasher.js:5.0.7
    container_name: moviemasher
    ports:
      - "8570:8570"
      - "8571:8571"
    volumes:
      - ../../packages:/home/node/app/packages
      - ../../temporary/example-express-react:/home/node/app/temporary
      - ../../docs:/home/node/app/docs
      - ../../workspaces/example-express-react:/home/node/app/workspaces/example-express-react
