FROM amazonlinux:2.0.20220316.0
LABEL org.opencontainers.image.authors="support@moviemasher.com"

WORKDIR /home/node/app

COPY package.json /home/node/app/package.json

COPY packages/moviemasher.js/package.json /home/node/app/packages/moviemasher.js/package.json
COPY packages/server-express/package.json /home/node/app/packages/server-express/package.json

COPY dev/image/sh /home/node/app/dev/image/sh
RUN sh /home/node/app/dev/image/sh/build-clean.sh

ENTRYPOINT ["node_modules/pm2/bin/pm2-docker"]
CMD ["start", "workspaces/example-express-react/host/server.js"]

COPY packages/moviemasher.js/umd/moviemasher.min.js /home/node/app/packages/moviemasher.js/umd/moviemasher.min.js
COPY packages/server-express/cjs/server-express.min.js /home/node/app/packages/server-express/cjs/server-express.min.js
COPY workspaces/example-express-react/host /home/node/app/workspaces/example-express-react/host
