ARG DIR_ROOT=/app
ARG MOVIEMASHER_VERSION=5.1.2
FROM moviemasher/node-ffmpeg:${MOVIEMASHER_VERSION} 
ARG DIR_ROOT
ARG MOVIEMASHER_VERSION

COPY package.json ${DIR_ROOT}/package.json

COPY images/test-server/package.json ${DIR_ROOT}/images/test-server/package.json
COPY packages/lib/shared/package.json ${DIR_ROOT}/packages/lib/shared/package.json
COPY packages/lib/server/package.json ${DIR_ROOT}/packages/lib/server/package.json

COPY packages/runtime/shared/package.json ${DIR_ROOT}/packages/runtime/shared/package.json
COPY packages/runtime/server/package.json ${DIR_ROOT}/packages/runtime/server/package.json

# TODO: remove me once shared lib does not depend on client
COPY packages/runtime/client/package.json ${DIR_ROOT}/packages/runtime/client/package.json

RUN npm install 

ENTRYPOINT ["npm", "run", "--workspace=@moviemasher/test-server"]
CMD ["test"]
LABEL org.opencontainers.image.authors="support@moviemasher.com"
