ARG DIR_ROOT=/app
ARG MOVIEMASHER_VERSION=5.2.0
FROM moviemasher/node-ffmpeg:${MOVIEMASHER_VERSION} 
ARG DIR_ROOT
ARG MOVIEMASHER_VERSION

COPY package.json ${DIR_ROOT}/package.json
COPY images/test-server/package.json ${DIR_ROOT}/images/test-server/package.json

RUN npm install 

ENTRYPOINT ["npm", "run", "--workspace=@moviemasher/test-server"]
CMD ["test"]
LABEL org.opencontainers.image.authors="support@moviemasher.com"

