version: "3"
name: moviemasher-test-server
services:
 service:
    env_file:
      - ../../../dev/local.env
    build: 
      context: ../../../
      dockerfile: images/test-server/dev/Dockerfile.cnf
    image: moviemasher/test-server:${MOVIEMASHER_VERSION}
    environment:
      - MOVIEMASHER_API_DIR_TEMPORARY=${MOVIEMASHER_DIR_ROOT}/temporary/test-server
      - MOVIEMASHER_API_DIR_CACHE=${MOVIEMASHER_DIR_ROOT}/temporary/test-server/cache
      - MOVIEMASHER_FOO=foo
    volumes:
      - ../../../package.json:${MOVIEMASHER_DIR_ROOT}/package.json
      - ../../../images/test-server:${MOVIEMASHER_DIR_ROOT}/images/test-server
      - ../../../dev/shared:${MOVIEMASHER_DIR_ROOT}/examples/express/public/shared
      - ../../../packages:${MOVIEMASHER_DIR_ROOT}/packages
      - ../../../temporary/test-server:${MOVIEMASHER_DIR_ROOT}/temporary/test-server

    