version: "3"
networks:
  default:
    name: test-rendering
services:
  test:
    image: moviemasher/moviemasher.js:5.1.0
    container_name: moviemasher-test-rendering
    entrypoint: node workspaces/test-rendering/dist/index.js
    command: ''
    volumes:
      - ../../../dev/:/home/node/app/dev/
      - ../../../packages/moviemasher.js/dist/:/home/node/app/packages/moviemasher.js/dist/
      - ../../../packages/server-express/dist/:/home/node/app/packages/server-express/dist/
      - ../../../workspaces/test-rendering/:/home/node/app/workspaces/test-rendering/
      - ../../../temporary/test-rendering/:/home/node/app/temporary/
      - ../../../package.json:/home/node/app/package.json