ARG DIR_ROOT=/app
ARG MOVIEMASHER_VERSION=5.1.2
FROM node:18 
ARG DIR_ROOT
ARG MOVIEMASHER_VERSION

WORKDIR ${DIR_ROOT}
COPY package.json ${DIR_ROOT}/package.json
COPY images/test-shared/package.json ${DIR_ROOT}/images/test-shared/package.json
COPY packages/core/lib/package.json ${DIR_ROOT}/packages/core/lib/package.json
COPY packages/runtime/shared/package.json ${DIR_ROOT}/packages/runtime/shared/package.json

RUN npm install 

ENTRYPOINT ["npm", "run", "--workspace=@moviemasher/test-shared"]
CMD ["test"]
LABEL org.opencontainers.image.authors="support@moviemasher.com"
