version: "3"
name: moviemasher-build-docs
services:
  service:
    build:
      dockerfile: images/build-docs/dev/Dockerfile.cnf
      context: ../../../
    image: moviemasher/build-docs:${MOVIEMASHER_VERSION}
    container_name: moviemasher-build-docs
    env_file:
      - ../../../dev/local.env
    
    volumes:
      - ../../../temporary/build-docs/:${MOVIEMASHER_DIR_ROOT}/temporary/build-docs/

      - ../../../docs/:${MOVIEMASHER_DIR_ROOT}/docs/
      - ../../../dev/:${MOVIEMASHER_DIR_ROOT}/dev/
      - ../../../examples/:${MOVIEMASHER_DIR_ROOT}/examples/

      - ../../../images/build-docs/dev/markdown.config.js:${MOVIEMASHER_DIR_ROOT}/markdown.config.js
      - ../../../README.md:${MOVIEMASHER_DIR_ROOT}/README.md

      - ../../../images/build-docs/dist:${MOVIEMASHER_DIR_ROOT}/images/build-docs/dist
      - ../../../images/build-docs/package.json:${MOVIEMASHER_DIR_ROOT}/package.json
      - ../../../images/build-docs/src:${MOVIEMASHER_DIR_ROOT}/images/build-docs/src

      - ../../../images/build-docs/dev/json.typedoc.cjs:${MOVIEMASHER_DIR_ROOT}/json.typedoc.cjs
      - ../../../images/build-docs/dev/md.typedoc.cjs:${MOVIEMASHER_DIR_ROOT}/md.typedoc.cjs
      - ../../../images/build-docs/dev/root.tsconfig.json:${MOVIEMASHER_DIR_ROOT}/tsconfig.json

      - ../../../packages/@moviemasher/client-lib:${MOVIEMASHER_DIR_ROOT}/packages/@moviemasher/client-lib
      - ../../../packages/@moviemasher/client-react:${MOVIEMASHER_DIR_ROOT}/packages/@moviemasher/client-react
      - ../../../packages/@moviemasher/server-express:${MOVIEMASHER_DIR_ROOT}/packages/@moviemasher/server-express
      - ../../../packages/@moviemasher/server-lib:${MOVIEMASHER_DIR_ROOT}/packages/@moviemasher/server-lib
      - ../../../packages/@moviemasher/shared-lib:${MOVIEMASHER_DIR_ROOT}/packages/@moviemasher/shared-lib