// this file is automatically generated from template at
// workspaces/translate/src/rollup.config.mjs

import { rollupConfigurations} from "../../../../dev/utils/rollupConfigurations.mjs"

const locale = 'fr'
const label = 'French'
const libName = `translate-${locale}`
const name = `MovieMasherTranslate${label}`
const configurations = rollupConfigurations({ name, libName })
export default configurations
