
FROM moviemasher/node-ffmpeg:5.2.0
ARG DIR_ROOT=/app

COPY package.json ${DIR_ROOT}/package.json

COPY packages/lib/client/package.json ${DIR_ROOT}/packages/lib/client/package.json
COPY packages/lib/client/dist ${DIR_ROOT}/packages/lib/client/dist

COPY packages/runtime/client/package.json ${DIR_ROOT}/packages/runtime/client/package.json
COPY packages/runtime/client/dist ${DIR_ROOT}/packages/runtime/client/dist

COPY images/express-ffmpeg/package.json ${DIR_ROOT}/images/express-ffmpeg/package.json

RUN npm install 

LABEL org.opencontainers.image.authors="support@moviemasher.com"