
FROM digitallyseamless/nodejs-bower-grunt:latest
MAINTAINER Movie Masher <support@moviemasher.com>

# # # # # # # # # #
#  NPM CONFIG
COPY ./package.json /data/package.json

# # # # # # # # # #
#  ADD BOWER/GRUNT
RUN npm install

