
FROM digitallyseamless/nodejs-bower-grunt:0.10
MAINTAINER Movie Masher <support@moviemasher.com>

# # # # # # # # # #
#  NPM CONFIG
COPY ./package.json /data/package.json

# # # # # # # # # #
#  ADD BOWER/GRUNT
RUN npm install

# # # # # # # # # #
#  DEFAULT COMMAND
CMD ["grunt"]
