version: "3"
name: moviemasher-example-client-component
services:
  service:
    image: httpd:2.4
    container_name: moviemasher-example-client-component-8578
    ports:
      - 8578:80
    volumes:
      - ../../../../dev/img/favicon.ico:/usr/local/apache2/htdocs/favicon.ico
      - ../../../../packages/core/lib/esm/:/usr/local/apache2/htdocs/@moviemasher/lib-core/esm
      - ../../../../packages/core/client/json/:/usr/local/apache2/htdocs/@moviemasher/client-core/json
      - ../../../../packages/core/client/esm/:/usr/local/apache2/htdocs/@moviemasher/client-core/esm
      - ../../../../packages/client/component/esm/:/usr/local/apache2/htdocs/@moviemasher/client-component/esm
      - ../../../../packages/client/component/example/src/index.html:/usr/local/apache2/htdocs/index.html
      - ../../../../node_modules/tslib:/usr/local/apache2/htdocs/tslib/
      - ../../../../node_modules/@lit:/usr/local/apache2/htdocs/@lit/
      - ../../../../node_modules/lit:/usr/local/apache2/htdocs/lit/
      - ../../../../node_modules/lit-html:/usr/local/apache2/htdocs/lit-html/
      - ../../../../node_modules/@lit-labs:/usr/local/apache2/htdocs/@lit-labs/
      - ../../../../node_modules/lit-element:/usr/local/apache2/htdocs/lit-element/
      
