ARG DIR_ROOT=/app

FROM amazonlinux:2023.1.20230825.0 AS code
ARG DIR_ROOT

# package JSON files from main and relevant projects
COPY package.json ${DIR_ROOT}/package.json
COPY images/node-ffmpeg/package.json ${DIR_ROOT}/images/node-ffmpeg/package.json

COPY packages/lib/shared/package.json ${DIR_ROOT}/packages/lib/shared/package.json
COPY packages/lib/shared/dist ${DIR_ROOT}/packages/lib/shared/dist

COPY packages/lib/server/package.json ${DIR_ROOT}/packages/lib/server/package.json
COPY packages/lib/server/dist ${DIR_ROOT}/packages/lib/server/dist

COPY packages/runtime/shared/package.json ${DIR_ROOT}/packages/runtime/shared/package.json
COPY packages/runtime/shared/dist ${DIR_ROOT}/packages/runtime/shared/dist

COPY packages/runtime/server/package.json ${DIR_ROOT}/packages/runtime/server/package.json
COPY packages/runtime/server/dist ${DIR_ROOT}/packages/runtime/server/dist

FROM amazonlinux:2023.1.20230825.0 
ARG DIR_ROOT
ARG OS_INSTALL=''
ARG OS_EXECUTE='npm install -g npm'

ARG INSTALL_NODE='18.17.1'
ARG INSTALL_NPM='--workspace=@moviemasher/node-ffmpeg'

WORKDIR ${DIR_ROOT}
COPY --from=code ${DIR_ROOT} ${DIR_ROOT}
COPY dev/image/sh ${DIR_ROOT}/dev/image/sh
RUN sh ${DIR_ROOT}/dev/image/sh/bases/build-aws2023.sh \
  -n "${INSTALL_NPM}" \
  -i "${INSTALL_NODE}" \
  -e "${OS_EXECUTE}" \
  -o "${OS_INSTALL}" \
  -r "${DIR_ROOT}"

LABEL org.opencontainers.image.authors="support@moviemasher.com"

# RUN cd /usr/local/src ; \
#   curl -O -L https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 ; \
#   tar xjvf ffmpeg-snapshot.tar.bz2 



# RUN cd /usr/local/src/ffmpeg ; \
#   PATH="/usr/bin:$PATH" LD_LIBRARY_PATH="/usr/lib:/usr/lib64" PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/lib64/pkgconfig" ./configure --prefix=/usr --bindir=/usr/bin --disable-debug --disable-doc --disable-ffplay --extra-cflags="-I/usr/include" --extra-ldflags="-L/usr/lib" --extra-libs=-lpthread --extra-libs=-lm --pkg-config-flags="--static" --enable-libharfbuzz --enable-libfribidi --enable-libfreetype --enable-libfontconfig --enable-gpl --enable-nonfree --enable-version3 --enable-libopenjpeg --enable-librsvg --enable-libx264 --enable-libfdk_aac --enable-libmp3lame --enable-libvpx  --enable-libspeex --enable-libtheora --enable-libvorbis  --enable-zlib --enable-libopus --enable-postproc --enable-pthreads --enable-swresample ; \
#   make tools/graph2dot; \
#   mv tools/graph2dot /usr/bin/; 



# RUN yum install -y libjpeg-devel libwebp-devel libzstd-devel jbigkit-devel
# COPY images/node-ffmpeg/dev/configure.sh /usr/local/src/ffmpeg-6.0/configure
# RUN chown 1000:1000 /usr/local/src/ffmpeg-6.0/configure; chmod +x /usr/local/src/ffmpeg-6.0/configure;

# RUN cd /usr/local/src/ffmpeg-6.0 ; \
#   PATH="/usr/bin:$PATH" LD_LIBRARY_PATH="/usr/lib:/usr/lib64" PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/lib64/pkgconfig" ./configure --prefix=/usr --bindir=/usr/bin --disable-debug --disable-doc --disable-ffplay --extra-cflags="-I/usr/include" --extra-ldflags="-L/usr/lib" --extra-libs=-lpthread --extra-libs=-lm --pkg-config-flags="--static" --enable-libfribidi --enable-libfreetype --enable-libfontconfig --enable-gpl --enable-nonfree --enable-version3 --enable-libopenjpeg --enable-librsvg --enable-libx264 --enable-libfdk_aac --enable-libmp3lame --enable-libvpx  --enable-libspeex --enable-libtheora --enable-libvorbis  --enable-zlib --enable-libopus --enable-postproc --enable-pthreads --enable-swresample ; \
#   make ; \
#   make install ;
# cat ffbuild/config.log exit 1;

# RUN find /usr/lib64 -name "*jpeg*" ; exit 1

# RUN echo lib ; ls -al /usr/lib/ | grep jpeg ; echo lib64 ; ls -al /usr/lib64/ | grep jpeg  ; exit 1;


# RUN ln -s /usr/include/librsvg-2.0 /usr/include/librsvg

# RUN ln -s /usr/lib64/pkgconfig/librsvg-2.0.pc /usr/lib64/pkgconfig/librsvg.pc 
# pkg-config --variable=includedir librsvg
# RUN cat /usr/include/librsvg-2.0/librsvg/rsvg.h ; \
#   exit 1;
# --cflags --print-errors librsvg-2.0

# COPY images/node-ffmpeg/dev/configure.sh /usr/local/src/ffmpeg-6.0/configure
# # chmod -X ./configure;

# --enable-libfontconfig --enable-libfreetype --enable-libspeex --enable-libtheora --enable-libvorbis  --enable-zlib --enable-libopus --enable-postproc --enable-pthreads --enable-swresample
# 0.181 -rwxr-xr-x  1 1000 1000 272037 Feb 27  2023 configure
# 0.190 -rw-r--r--  1 root root 272038 Sep  8 16:26 configure
# cat ./configure ./; 
# RUN yum install -y findutils 
# RUN find / -name "*librsvg*"
# # RUN dnf update -y ;
# # RUN dnf provides find

# # FFmpeg expect to find librsvg rather than librsvg-2.0, as AL3 installs it.
# RUN ln -s /usr/include/librsvg-2.0 /usr/include/librsvg
# RUN ln -s /usr/lib64/pkgconfig/librsvg-2.0.pc /usr/lib64/pkgconfig/librsvg.pc 



# # FFmpeg expects to find librsvg rather than librsvg-2.0, as AL3 installs it.
# RUN ln -s /usr/include/librsvg-2.0 /usr/include/librsvg
# RUN ln -s /usr/lib64/pkgconfig/librsvg-2.0.pc /usr/lib64/pkgconfig/librsvg.pc 

# RUN /sbin/ldconfig /usr/lib64
