ARG DIR_ROOT=/app

FROM amazonlinux:2023.3.20231218.0 AS code
ARG DIR_ROOT

COPY package.json ${DIR_ROOT}/package.json
COPY images/node-ffmpeg/package.json ${DIR_ROOT}/images/node-ffmpeg/package.json

COPY packages/@moviemasher/shared-lib/package.json ${DIR_ROOT}/packages/@moviemasher/shared-lib/package.json
COPY packages/@moviemasher/shared-lib/dist ${DIR_ROOT}/packages/@moviemasher/shared-lib/dist

COPY packages/@moviemasher/server-lib/package.json ${DIR_ROOT}/packages/@moviemasher/server-lib/package.json
COPY packages/@moviemasher/server-lib/dist ${DIR_ROOT}/packages/@moviemasher/server-lib/dist

FROM amazonlinux:2023.3.20231218.0 
ARG DIR_ROOT
ARG OS_INSTALL=''
ARG OS_EXECUTE='npm install -g npm'

ARG INSTALL_NODE='18.17.1'
ARG INSTALL_NPM='--workspace=@moviemasher/node-ffmpeg'

WORKDIR ${DIR_ROOT}
COPY --from=code ${DIR_ROOT} ${DIR_ROOT}
COPY dev/image/sh ${DIR_ROOT}/dev/image/sh
RUN sh ${DIR_ROOT}/dev/image/sh/bases/build-aws2023.sh \
  -n "${INSTALL_NPM}" \
  -i "${INSTALL_NODE}" \
  -e "${OS_EXECUTE}" \
  -o "${OS_INSTALL}" \
  -r "${DIR_ROOT}"

LABEL org.opencontainers.image.authors="support@moviemasher.com"
