version: "3"
name: moviemasher-node-ffmpeg
services:
 service:
    env_file:
      - ../../../dev/local.env
    build: 
      context: ../../../
      dockerfile: images/node-ffmpeg/dev/Dockerfile.cnf
    image: moviemasher/node-ffmpeg:${MOVIEMASHER_VERSION}
    