import type { ClientAction } from '@moviemasher/runtime-client'

export const ClientActionRedo: ClientAction = 'redo'
export const ClientActionRemove: ClientAction = 'remove'
export const ClientActionRender: ClientAction = 'render'
export const ClientActionSave: ClientAction = 'save'
export const ClientActionUndo: ClientAction = 'undo'
export const ClientActionAdd: ClientAction = 'add'
export const ClientActionAddTrack: ClientAction = 'add-track'
export const ClientActionFlip: ClientAction = 'flip'
export const ClientActionTogglePaused: ClientAction = 'toggle-paused'
