ARG DIR_ROOT=/app

FROM amazonlinux:2022 AS copy
ARG DIR_ROOT

# package JSON files from main and all utilized workspaces
COPY package.json ${DIR_ROOT}/package.json
COPY packages/core/lib/package.json ${DIR_ROOT}/packages/core/lib/package.json
COPY packages/server/express/package.json ${DIR_ROOT}/packages/server/express/package.json
COPY packages/core/server/package.json ${DIR_ROOT}/packages/core/server/package.json
COPY packages/theme/default/package.json ${DIR_ROOT}/packages/theme/default/package.json
COPY packages/client/react/package.json ${DIR_ROOT}/packages/client/react/package.json
COPY packages/core/client/package.json ${DIR_ROOT}/packages/core/client/package.json
COPY examples/standalone/package.json ${DIR_ROOT}/examples/standalone/package.json

# standalone server and entire public directory (includes client)
COPY examples/standalone/private/server.mjs ${DIR_ROOT}/examples/standalone/private/server.mjs
COPY examples/standalone/public ${DIR_ROOT}/examples/standalone/public

# public graphics (shared between images)
COPY dev/img/favicon.ico ${DIR_ROOT}/examples/standalone/public/favicon.ico
COPY dev/img/mm.svg ${DIR_ROOT}/examples/standalone/public/mm.svg

# client package JSON UMD modules (loaded directly from HTML)
COPY packages/core/lib/umd/moviemasher.js ${DIR_ROOT}/examples/standalone/public/moviemasher.js
COPY packages/core/client/umd/client-core.js ${DIR_ROOT}/examples/standalone/public/client-core.js
COPY packages/client/react/umd/client-react.js ${DIR_ROOT}/examples/standalone/public/client-react.js
COPY packages/theme/default/moviemasher.css ${DIR_ROOT}/examples/standalone/public/moviemasher.css
COPY packages/theme/default/umd/theme-default.js ${DIR_ROOT}/examples/standalone/public/theme-default.js

# server ESM files
COPY packages/core/lib/esm ${DIR_ROOT}/packages/core/lib/esm
COPY packages/core/server/esm ${DIR_ROOT}/packages/core/server/esm
COPY packages/server/express/esm ${DIR_ROOT}/packages/server/express/esm

# database migrations (shared between images)
COPY dev/data-migrations ${DIR_ROOT}/dev/data-migrations

FROM amazonlinux:2022 as run
ARG DIR_ROOT
ARG OS_INSTALL='nodejs postgresql14'
ARG OS_EXECUTE='npm install -g npm'
ARG NPM_INSTALL='--workspace=@moviemasher/example-standalone'

WORKDIR ${DIR_ROOT}
COPY --from=copy ${DIR_ROOT} ${DIR_ROOT}
COPY dev/image/sh ${DIR_ROOT}/dev/image/sh
RUN sh ${DIR_ROOT}/dev/image/sh/bases/build-aws2022.sh \
  -o "${OS_INSTALL}" \
  -e "${OS_EXECUTE}" \
  -n "${NPM_INSTALL}" \
  -r ${DIR_ROOT}

# link React/DOM UMD modules into public directory 
RUN ln -s ${DIR_ROOT}/node_modules/react/umd/react.production.min.js ${DIR_ROOT}/examples/standalone/public/react.js
RUN ln -s ${DIR_ROOT}/node_modules/react-dom/umd/react-dom.production.min.js ${DIR_ROOT}/examples/standalone/public/react-dom.js

LABEL org.opencontainers.image.authors="support@moviemasher.com"